name: calendar_day_view
description: This package is dedicated to calendar day view. This library is to be used with calendar in the app that need better day views
version: 1.1.4
homepage: https://github.com/samderlust/calendar_day_view

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
