name: calendar_day_view
description: This package is dedicated to calendar day view. This is a complement to calendar to make your app better
version: 1.3.0
homepage: https://github.com/samderlust/calendar_day_view

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_pointer: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
